# Generated by Django 3.2.6 on 2021-08-14 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=64)),
                ('price', models.PositiveIntegerField()),
                ('priceSP', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField()),
                ('value_fields', models.CharField(max_length=64)),
                ('measurment_unit', models.CharField(max_length=16)),
                ('picture', models.CharField(max_length=64)),
                ('show_on_mainpage', models.BooleanField()),
                ('description', models.TextField()),
            ],
        ),
    ]
