# Generated by Django 3.2.6 on 2021-08-15 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_app', '0004_auto_20210815_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='price',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='data',
            name='priceSP',
            field=models.CharField(max_length=16),
        ),
    ]
