# Generated by Django 3.2.6 on 2021-08-15 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_app', '0005_auto_20210815_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='data',
            name='priceSP',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
