# Generated by Django 3.2.6 on 2021-08-15 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_app', '0006_auto_20210815_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
