# Generated by Django 3.2.6 on 2021-08-15 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_app', '0007_alter_data_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='data',
            name='priceSP',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
